"""RecieveDate

Revision ID: 8f50918a44de
Revises: d3e4f5db2594
Create Date: 2021-07-16 08:37:21.463343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f50918a44de'
down_revision = 'd3e4f5db2594'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('recievedDate', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate', 'recievedDate')
    # ### end Alembic commands ###
